import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import 'services/storage_service.dart';

class HistoryScreen extends StatefulWidget {
  const HistoryScreen({super.key});

  @override
  State<HistoryScreen> createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> {
  final StorageService _storageService = StorageService();
  List<Map<String, dynamic>> _alerts = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  Future<void> _loadHistory() async {
    final alerts = await _storageService.getAlertHistory();
    setState(() {
      _alerts = alerts;
      _isLoading = false;
    });
  }

  // 🚨 NEW: Generates a clean text report and opens the Share Sheet
  void _exportEvidence(Map<String, dynamic> alert) {
    final String report = '''
🚨 CALLSHIELD-AI: CYBER THREAT REPORT 🚨

Date/Time: ${alert['timestamp'] ?? 'Unknown'}
Threat Level: ${alert['threatLevel']}
Scam Probability: ${alert['probability']}%

AI Analysis & Tactics Used:
${alert['explanation']}

This evidence was automatically generated by CallShield-AI to assist law enforcement.
''';
    Share.share(report, subject: 'Cyber Fraud Evidence Report');
  }

  // 🚨 NEW: Opens the official Indian Cyber Crime Portal
  Future<void> _launchCyberPortal() async {
    final Uri url = Uri.parse('https://cybercrime.gov.in/');
    if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
      debugPrint('Could not launch cybercrime portal');
    }
  }

  // 🚨 NEW: Dials the 1930 Helpline
  Future<void> _callHelpline() async {
    final Uri phoneUri = Uri(scheme: 'tel', path: '1930');
    if (!await launchUrl(phoneUri)) {
      debugPrint('Could not launch dialer');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        backgroundColor: const Color(0xFF0F172A),
        elevation: 0,
        title: Text(
          'Threat Dashboard',
          style: GoogleFonts.plusJakartaSans(fontWeight: FontWeight.bold, color: Colors.white),
        ),
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          IconButton(
            icon: const Icon(Icons.delete_sweep, color: Colors.grey),
            onPressed: () async {
              await _storageService.clearHistory();
              _loadHistory();
            },
          )
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF6366F1)))
          : _alerts.isEmpty
          ? Center(
        child: Text(
          "No threats detected yet.\nYou are secure.",
          textAlign: TextAlign.center,
          style: GoogleFonts.plusJakartaSans(color: Colors.grey, fontSize: 16),
        ),
      )
          : ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: _alerts.length,
        itemBuilder: (context, index) {
          final alert = _alerts[index];
          final isCritical = alert['threatLevel'] == 'CRITICAL';
          final color = isCritical ? const Color(0xFFEF4444) : const Color(0xFFF59E0B);

          return Container(
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: const Color(0xFF1E293B),
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: color.withOpacity(0.3), width: 1),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Card Content
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Icon(Icons.warning_rounded, color: color, size: 24),
                              const SizedBox(width: 8),
                              Text(
                                isCritical ? 'CRITICAL THREAT' : 'SUSPICIOUS',
                                style: GoogleFonts.plusJakartaSans(
                                  color: color,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 14,
                                ),
                              ),
                            ],
                          ),
                          Text(
                            '${alert['probability']}% Match',
                            style: GoogleFonts.plusJakartaSans(color: Colors.white, fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                      const Padding(
                        padding: EdgeInsets.symmetric(vertical: 12),
                        child: Divider(color: Colors.white12),
                      ),
                      Text(
                        alert['explanation'] ?? 'No details provided.',
                        style: GoogleFonts.plusJakartaSans(color: const Color(0xFF94A3B8), fontSize: 14),
                      ),
                    ],
                  ),
                ),
                // 🚨 NEW: The Action Bar
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: const BoxDecoration(
                    color: Color(0xFF0F172A),
                    borderRadius: BorderRadius.only(
                      bottomLeft: Radius.circular(20),
                      bottomRight: Radius.circular(20),
                    ),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      TextButton.icon(
                        icon: const Icon(Icons.share, size: 16, color: Color(0xFF6366F1)),
                        label: Text("Evidence", style: GoogleFonts.plusJakartaSans(color: const Color(0xFF6366F1), fontSize: 13)),
                        onPressed: () => _exportEvidence(alert),
                      ),
                      TextButton.icon(
                        icon: const Icon(Icons.phone_in_talk, size: 16, color: Colors.greenAccent),
                        label: Text("1930", style: GoogleFonts.plusJakartaSans(color: Colors.greenAccent, fontSize: 13)),
                        onPressed: _callHelpline,
                      ),
                      TextButton.icon(
                        icon: const Icon(Icons.local_police, size: 16, color: Color(0xFFEF4444)),
                        label: Text("Portal", style: GoogleFonts.plusJakartaSans(color: const Color(0xFFEF4444), fontSize: 13)),
                        onPressed: _launchCyberPortal,
                      ),
                    ],
                  ),
                )
              ],
            ),
          );
        },
      ),
    );
  }
}