import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:share_plus/share_plus.dart';

class ThreatDashboard extends StatefulWidget {
  const ThreatDashboard({super.key});

  @override
  State<ThreatDashboard> createState() => _ThreatDashboardState();
}

class _ThreatDashboardState extends State<ThreatDashboard> {
  List<dynamic> _threatHistory = [];

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  Future<void> _loadHistory() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.reload();
    List<String> rawHistory = prefs.getStringList('threat_dashboard') ?? [];
    setState(() {
      _threatHistory = rawHistory.map((e) => jsonDecode(e)).toList();
    });
  }

  // 🚨 The 1-Click Cyber Cell Dispatch
  Future<void> _sendToCyberCell(String pdfPath, String callerId) async {
    final Email email = Email(
      body: 'To the Cyber Crime Unit,\n\nPlease find attached the automated forensic incident report generated by CallShield AI. This document contains the AI threat verdict, identified social engineering tactics, and the redacted transcript of the scam call originating from $callerId.\n\nThank you.',
      subject: 'URGENT: CallShield AI Incident Report - Telecom Fraud ($callerId)',
      recipients: ['report@cybercrime.gov.in'],
      attachmentPaths: [pdfPath],
      isHTML: false,
    );
    try {
      await FlutterEmailSender.send(email);
    } catch (e) {
      debugPrint("Email Error: $e");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        title: Text("Threat Dashboard", style: GoogleFonts.plusJakartaSans(fontWeight: FontWeight.bold)),
        backgroundColor: const Color(0xFF0F172A),
        elevation: 0,
      ),
      body: _threatHistory.isEmpty
          ? Center(child: Text("No threats detected yet.", style: GoogleFonts.plusJakartaSans(color: Colors.grey)))
          : ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: _threatHistory.length,
        itemBuilder: (context, index) {
          final item = _threatHistory[index];
          final String callerId = item['callerId'] ?? 'Unknown Number';
          final String maxThreat = item['maxThreat'].toString();
          final List<dynamic> tactics = item['tactics'] ?? [];
          final String pdfPath = item['pdfPath'];

          DateTime dt = DateTime.parse(item['timestamp']);
          String timeString = "${dt.day}/${dt.month}/${dt.year} - ${dt.hour}:${dt.minute.toString().padLeft(2, '0')}";

          return Container(
            margin: const EdgeInsets.only(bottom: 16),
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: const Color(0xFF1E1E2A),
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFFEF4444).withOpacity(0.3)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      children: [
                        const Icon(Icons.shield, color: Color(0xFFEF4444), size: 24),
                        const SizedBox(width: 8),
                        Text(callerId, style: GoogleFonts.plusJakartaSans(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
                      ],
                    ),
                    Text(timeString, style: GoogleFonts.plusJakartaSans(color: Colors.grey[500], fontSize: 12)),
                  ],
                ),
                const SizedBox(height: 16),
                Text("Max Threat Level: $maxThreat% (Critical)", style: GoogleFonts.plusJakartaSans(color: const Color(0xFFEF4444), fontWeight: FontWeight.bold)),
                const SizedBox(height: 4),
                Text("Tactics: ${tactics.join(', ')}", style: GoogleFonts.plusJakartaSans(color: Colors.grey[400], fontSize: 13)),
                const Divider(color: Colors.white10, height: 32),

                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        style: OutlinedButton.styleFrom(
                          foregroundColor: Colors.white,
                          side: BorderSide(color: Colors.white.withOpacity(0.2)),
                        ),
                        icon: const Icon(Icons.picture_as_pdf, size: 16),
                        label: const Text("View PDF"),
                        onPressed: () {
                          Share.shareXFiles([XFile(pdfPath)], text: "CallShield Forensic Report");
                        },
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: ElevatedButton.icon(
                        style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFFEF4444), foregroundColor: Colors.white),
                        icon: const Icon(Icons.send, size: 16),
                        label: const Text("Report"),
                        onPressed: () => _sendToCyberCell(pdfPath, callerId),
                      ),
                    )
                  ],
                )
              ],
            ),
          );
        },
      ),
    );
  }
}